#!/bin/sh

if test -z "$1"
then
    echo "syntax: $0 PATH-TO-LCITOOL"
    exit 1
fi

LCITOOL=$1

if ! test -x "$LCITOOL"
then
    echo "$LCITOOL is not executable"
    exit 1
fi

HOSTS=$($LCITOOL hosts | grep -v -E '(freebsd|macos)')

for host in $HOSTS
do
    if test "$host" = "fedora-rawhide"
    then
        for cross in mingw32 mingw64
        do
            $LCITOOL dockerfile $host libvirt,libvirt-glib --cross $cross > ci-$host-cross-$cross.Dockerfile
        done
    fi

    if test "$host" = "centos-8"
    then
        $LCITOOL dockerfile $host libvirt+minimal,libvirt+dist,libvirt-glib > ci-$host.Dockerfile
    else
        $LCITOOL dockerfile $host libvirt+dist,libvirt-glib > ci-$host.Dockerfile
    fi
done
